name: Build / Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [macos, ios, tvos]

    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: make build-test-${{ matrix.platform }}

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: TestResults
