name: Build / Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict


  build-test-coverage:
  
    runs-on: macos-latest

    needs: [check]

    steps:
      
    - uses: actions/checkout@v2

    - name: Build/Test
      run: make build-test-macos

    - name: Test Coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
        output-file: ./coverage/lcov.info

    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: TestResults


  build-test:
    runs-on: macos-latest

    needs: [check]

    strategy:
      matrix:
        platform: [ios, tvos]

    steps:

    - uses: actions/checkout@v2

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: TestResults
