name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v1
    - name: SwiftLint
      run: ./.github/swiftlinter      

  build-test:
  
    runs-on: macos-latest

    needs: [check]

    strategy:
      matrix:
        platform: [macos, ios, tvos]
        xcode: ["12.5.1", "13.0"]

    steps:
      
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Test Coverage
      uses: maxep/spm-lcov-action@0.3.0
      if: ${{ matrix.platform == 'macos' && matrix.xcode == '12.5.1' }}
      with:
        output-file: ./coverage/lcov.info

    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.2.21
      if: ${{ matrix.platform == 'macos' && matrix.xcode == '12.5.1' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: TestResults
