name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:

  check-build-test:
    runs-on: macos-12

    steps:

    - name: Install Tools
      run: |
        brew install xcbeautify
        brew install sonar-scanner

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: SwiftLint
      run: |
        mkdir .build
        swiftlint lint --reporter json > .build/swiftlint.json

    - name: Build/Test
      run: set -o pipefail && swift test --enable-code-coverage --sanitize undefined | xcbeautify

    - name: Convert Coverage
      run: xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/SundayPackageTests.xctest/Contents/MacOS/SundayPackageTests > .build/coverage.report

    - name: Sonar Scanner
      run: sonar-scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build-test:
  
    runs-on: macos-12

    needs: [check-build-test]

    strategy:
      matrix:
        platform: [macos, ios, tvos]

    steps:
      
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: Install Tools
      run: brew install xcbeautify

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Report Test Results
      uses: kishikawakatsumi/xcresulttool@v1
      if: always()
      with:
          title: Test Results ${{ matrix.platform }}
          path: ./TestResults/${{ matrix.platform }}.xcresult
