name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:

  check:
    runs-on: macos-12

    steps:

    - uses: actions/checkout@v1
    - name: SwiftLint
      run: ./.github/swiftlinter      

  build-test:
  
    runs-on: macos-12

    needs: [check]

    strategy:
      matrix:
        platform: [macos, ios, tvos]
        xcode: ["14.1"]

    steps:
      
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Build/Test
      run: |
        make build-test-${{ matrix.platform }}

    - name: Export Coverage
      id: coverage-files
      uses: sersoft-gmbh/swift-coverage-action@v3

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}
